            # Retail Sales dataset
# Product ID	Price	Quantity Sold	Total Revenue
# 101	        15.99	     200	          3198
# 102	        45.5	     120	          5460
# 103	        29.99	     80	              2399.2
# 104	        10	         500	          5000
# 105	        99.99	     450	          44995.5
# 106	        2.5	         110	          275
# 107       	12.3	     209	          2570.7
# 108	        101.99	     180	          18358.2
# 109	        200	         1000	          200000
# 110	        10.9	     200	          2180
# ---------------------------------------------------------------

# Column indices for clarity
PRODUCT_ID, PRICE, QUANTITY_SOLD, TOTAL_REVENUE = 0, 1, 2, 3

import numpy as np
data =np.array([
    [101, 15.99, 200, 3198.0],
    [102, 45.50, 120, 5460.0],
    [103, 29.99, 80, 2399.2],
    [104, 10.00, 500, 5000.0],
    [105, 99.99, 60, 5999.4],
    [106, 2.50, 1000, 2500.0],
    [107,12.30,209,2570.7],
    [108,101.99,180,18358.2],
    [109,200,1000,20000],
    [110,10.90,200,2180],
])

if np.isnan(data).any():
    print("Warning! The dataset contains missing values")
else:
    print("Dataset is clean")

#Point 1 : Calculate revenue generated by all products
total_revenue = np.sum(data[:,TOTAL_REVENUE])
print(f"Total Revenue generated: ${total_revenue:.2f}")

#Point 2 : Product with the highest quantity sold
most_sold_product_index = np.argmax(data[:,QUANTITY_SOLD])
most_sold_product = data[most_sold_product_index]
print(f"Most popular product (ID: {most_sold_product[PRODUCT_ID]}) with {most_sold_product[QUANTITY_SOLD]} units sold.")

#Point 3 : Average selling price of all products
average_price = np.mean(data[:,PRICE])
print(f"Average Selling Price: ${average_price:.2f}")

#Point 4 : Filter products with revenue above a threshold
threshold = 2500
high_revenue_products = data[data[:,TOTAL_REVENUE] > threshold]
print(f"Products with revenue above ${threshold}:")
for product in high_revenue_products:
    print(f"Product ID: {product[PRODUCT_ID]}, Revenue: ${product[TOTAL_REVENUE]:.2f}")